# release data downloaded to disk
data_root: /home/motion/data/scannet_pp
scene_list_file: /home/motion/data/scannet_pp/splits/nvs_sem_train.txt
filter_scenes: []

# image type - iphone or dslr
image_type: iphone

no_log: true

# subsample images 
subsample_factor: 10
# downsample images and rasterize
image_downsample_factor: null

rasterout_dir: /home/motion/data/scannet_pp

limit_images: None

wandb_group: null
wandb_notes: null

batch_size: 50
limit_batches: null
skip_existing: false