############### input data #################
# release data downloaded to disk
data_root:  /home/motion/data/scannet_pp/data
scene_list_file: /home/motion/data/scannet_pp/splits/nvs_sem_train.txt
rasterout_dir: /home/motion/data/scannet_pp
visiblity_cache_dir: null
filter_scenes: []
exclude_scenes: []
# image type - iphone or dslr
image_type: iphone
undistort_dslr: true
create_visiblity_cache_only: false

########## tasks/data to be created ##########
save_semantic_gt_2d: True
semantic_classes_file: /home/motion/data/scannet_pp/metadata/semantic_benchmark/top100.txt
viz_semantic_gt_2d: false
semantic_2d_palette_path: null

############### hyperparams #################
check_visibility: false
# use topk views with visiblity of object vertices
visibility_topk: 3
# min size of the bbox of an object (each side must be greater than this in pixels)
bbox_min_side_pix: 50
# subsample images 
subsample_factor: 20
# atleast this fraction of the object's vertices should be visible in the image
# set to 0 to ignore threshold
obj_visible_thresh: 0.1
# object should cover atleast this fraction of the image's pixels
# set to 0 to ignore threshold
obj_pixel_thresh: 0.00
# object should be within this distance from the camera (meters) (set large number to include all objects)
obj_dist_thresh: 999
# expand the bbox by this fraction in each direction
bbox_expand_factor: 0.1

############### output #################
save_dir_root:  /home/motion/data/scannet_pp
save_dir: test

############### dbg #################
dbg:
  # viz obj ids in 2d for each image
  viz_obj_ids: true